import { NestFactory } from '@nestjs/core';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import { apiReference } from '@scalar/nestjs-api-reference';
import { LoggingInterceptor } from '@/common/interceptors/logging.interceptor';
import { AppModule } from '@/app.module';

async function bootstrap() {
	// Disable bodyParser for compatibility with Better-Auth
	const app = await NestFactory.create(AppModule, { bodyParser: false });

	// Add logging interceptor to monitor requests and responses
	app.useGlobalInterceptors(new LoggingInterceptor());

	// Enable CORS
	app.enableCors({
		origin: process.env.FRONTEND_URL,
		credentials: true,
	});

	// Enable Scalar API Docs
	const config = new DocumentBuilder()
		.setTitle('Turborepo Starter API Documentation')
		.setDescription(
			'This API Documentation outlines the endpoints for the Turborepo Starter project. Generated by Scalar API Docs.',
		)
		.setVersion('1.0')
		.build();
	const document = SwaggerModule.createDocument(app, config);
	SwaggerModule.setup('api', app, document, { swaggerUiEnabled: false });
	app.use(
		'/api/docs',
		apiReference({
			spec: {
				content: document,
			},
			hideModels: true,
			theme: 'default',
			layout: 'modern',
			documentDownloadType: 'none',
			darkMode: true,
			hideDarkModeToggle: false,
			defaultHttpClient: {
				targetKey: 'node',
				clientKey: 'undici',
			},
			hiddenClients: true,
		}),
	);

	// Start server on port 3000
	await app.listen(3000);
}
bootstrap();
